# Generated by Django 4.2 on 2024-03-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseForWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineName', models.CharField(max_length=60)),
                ('nameBaseTable', models.CharField(max_length=100)),
                ('TimeSecUpdate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLCName', models.CharField(max_length=100)),
                ('chamber', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.line')),
            ],
        ),
        migrations.CreateModel(
            name='CurtecSensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('ValueName', models.CharField(max_length=255)),
                ('Value', models.FloatField()),
                ('PLC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.plc')),
            ],
        ),
    ]
