# Generated by Django 4.2 on 2024-03-22 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='nameBaseTable',
        ),
        migrations.AddField(
            model_name='baseforwrite',
            name='nameBaseTable',
            field=models.CharField(default='CurtecData', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.baseforwrite'),
            preserve_default=False,
        ),
    ]
