# Generated by Django 4.2 on 2024-02-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineName', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='curtecsensors',
            old_name='NameValue',
            new_name='ValueName',
        ),
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLCName', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.line')),
            ],
        ),
        migrations.CreateModel(
            name='BaseForWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('table', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.line')),
            ],
        ),
        migrations.AddField(
            model_name='curtecsensors',
            name='PLC',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='laboratory.plc'),
            preserve_default=False,
        ),
    ]
