# Generated by Django 4.2 on 2024-02-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_line_rename_namevalue_curtecsensors_valuename_plc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plc',
            name='chamber',
            field=models.CharField(default='1_2', max_length=100),
            preserve_default=False,
        ),
    ]
