# Generated by Django 4.2 on 2024-02-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_plc_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtecsensors',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
