# Generated by Django 4.2 on 2024-01-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPrintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PalNo', models.IntegerField(null=True)),
                ('NumProd', models.IntegerField(null=True)),
                ('Timestamp', models.DateTimeField(null=True)),
                ('Barcode', models.CharField(max_length=255, null=True)),
                ('Product', models.TextField(null=True)),
                ('StatusPrint', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'LocalPrintHistory',
            },
        ),
    ]
