# Generated by Django 4.2 on 2024-01-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmp260_line_1', '0002_alter_localprinthistory_statusprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localprinthistory',
            name='Timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
