# Generated by Django 4.2 on 2024-01-18 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmp260_line_1', '0003_alter_localprinthistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='localprinthistory',
            name='add_datatime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 10, 58, 16, 804108)),
        ),
    ]
