# Generated by Django 4.2 on 2024-01-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmp260_line_1', '0004_localprinthistory_add_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localprinthistory',
            name='add_datatime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
